### ISSUE TITLE
TimeoutError when calling Storage.upload

### ISSUE THREAD

**Issue by rubik** [talkiq/gcloud-aio#137]
`gcloud-aio-storage` v5.1.0 (latest). I'm calling `Storage.upload()` with a file object, and after a while it fails with the following traceback:

```python
~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/gcloud/aio/storage/storage.py in upload(self, bucket, object_name, file_data, content_type, parameters, headers, metadata, session, timeout, force_resumable_upload)
    207             if metadata:
    208                 log.warning('metadata will be ignored for upload_type=Simple')
--> 209             return await self._upload_simple(url, object_name, stream,
    210                                              parameters, headers,
    211                                              session=session, timeout=timeout)

~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/gcloud/aio/storage/storage.py in _upload_simple(self, url, object_name, stream, params, headers, session, timeout)
    306 
    307         s = AioSession(session) if session else self.session
--> 308         resp = await s.post(url, data=stream, headers=headers, params=params,
    309                             timeout=timeout)
    310         data: dict = await resp.json()

~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/gcloud/aio/auth/session.py in post(self, url, headers, data, timeout, params)
     63                        params: Dict[str, str] = None
     64                        ) -> aiohttp.ClientResponse:
---> 65             resp = await self.session.post(url, data=data, headers=headers,
     66                                            timeout=timeout, params=params)
     67             resp.raise_for_status()

~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/aiohttp/client.py in _request(self, method, str_or_url, params, data, json, cookies, headers, skip_auto_headers, auth, allow_redirects, max_redirects, compress, chunked, expect100, raise_for_status, read_until_eof, proxy, proxy_auth, timeout, verify_ssl, fingerprint, ssl_context, ssl, proxy_headers, trace_request_ctx)
    502                             resp = await req.send(conn)
    503                             try:
--> 504                                 await resp.start(conn)
    505                             except BaseException:
    506                                 resp.close()

~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/aiohttp/client_reqrep.py in start(self, connection)
    858                 if self._continue is not None:
    859                     set_result(self._continue, True)
--> 860                     self._continue = None
    861 
    862         # payload eof handler

~/.local/share/virtualenvs/backend/lib/python3.8/site-packages/aiohttp/helpers.py in __exit__(self, exc_type, exc_val, exc_tb)
    594 
    595         if exc_type is asyncio.CancelledError and self._cancelled:
--> 596             raise asyncio.TimeoutError from None
    597         return None
    598 

TimeoutError: 
```

The service account exists and has the permissions required.

**Comment by mozbhearsum** [comment]
I'm curious what your call looks like. Perhaps it's a legitimate timeout? The default timeout is 30s (https://github.com/talkiq/gcloud-aio/blob/master/storage/gcloud/aio/storage/storage.py#L176).

**Comment by rubik** [comment]
@mozbhearsum My call is pretty simple. I'm not overriding any connection parameter:

```python
            upload_data = await ctx['storage'].upload(
                bucket='XXX',
                object_name=filename,
                file_data=fobj.read(),
                content_type='text/csv',
            )
```

**Comment by mozbhearsum** [comment]
Is it timing out after 30s? If so, you're probably hitting the default timeout.

**Comment by rubik** [comment]
@mozbhearsum Yes, but without any apparent reason. My internet connection is not a problem. DNS shouldn't be either.

**Comment by mozbhearsum** [comment]
> @mozbhearsum Yes, but without any apparent reason. My internet connection is not a problem. DNS shouldn't be either.

:man_shrugging: You can try bumping it if you pass a `session` object in that overrides the timeout, I believe. Good luck!

**Comment by TheKevJames** [comment]
With respect to library usage, you can either do as @mozbhearsum suggested or make use of the `timeout` argument to the `Storage.upload()` method itself ([see code](https://github.com/talkiq/gcloud-aio/blob/e35edb800ee6a42e583eafa7bf3dc1f03e6a2f63/storage/gcloud/aio/storage/storage.py#L173)) which defaults to 30s.

I'm not sure how helpful we'll be on why the timeout is occurring itself -- in my own team's usage, we've certainly noticed that Google Cloud's APIs timeout and/or return server errors a bit more than we'd expect. Personally, we like to set the timeout as low as possible based on the expected size of the upload and then make use of a retry handler -- the [backoff](https://pypi.org/project/backoff/) library is great if you're looking for something which support exponential backoff with jitter, which tends to be the recommendation when dealing with HTTP APIs.

@rubik please let me know if you're seeing any issues with the library itself and feel free to reopen this issue! Closing as this seems to be a Google issue.

(sorry for the late response on this -- I seem to have disabled notifications on new issues on this repo; should be fixed now!)

**Comment by rubik** [comment]
@TheKevJames Thanks for the suggestions. I will definitely report more issues if I encounter them.
