### ISSUE TITLE
Add retries to gcloud.aio.storage.Storage._download and _upload_simple, just as in _upload_resumable

### ISSUE THREAD

**Issue by DaniilAnichin** [talkiq/gcloud-aio#156]
The point is, gcloud storage api is fairly unstable and is known for throwing random 503 / 500 / etc errors from time to time. Right now I have to implement retries in my app. The case is pretty similar to the one described in [Issue#137](https://github.com/talkiq/gcloud-aio/issues/137)
Same applies to gcloud.aio.auth metadata calls, actually
If you'll decide that this is a good thing to do, I'll prepare PR and tag you, and so on.

**Comment by TheKevJames** [comment]
I am generally of the opinion that it's better for libraries to avoid being overly opinionated -- what seems like sane defaults from our perspective might be completely incorrect for a different usecase. Within my own company's stack, I can count offhand at least half a dozen very different retry mechanisms we use in different places.

I think the best middle ground might be to provide some documentation on suggested ways to integrate an external retry handler with this library -- as I mentioned in #137, I'm a fan of the [backoff](https://pypi.org/project/backoff/) library, but I'd be willing to accept a documentation PR making use of any external solution!

**Comment by ybressler** [comment]
I'm encountering a similar issue and would like to implement the `backoff` module as a solution. Could you point me to the documentation / where I can submit a PR with solution? @TheKevJames

**Comment by TheKevJames** [comment]
@ybressler Absolutely! As a quick example, you might do something along the lines of:

```python
import aiohttp
import backoff
from gcloud.aio.storage import Storage

@backoff.on_exception(backoff.expo, aiohttp.ClientResponseError, max_time=10)  # see https://pypi.org/project/backoff/
async def fetch_my_file(storage_client: Storage) -> bytes:
    await storage_client.download('my-gcs-bucket', 'path/to/file')
```

**Comment by TheKevJames** [comment]
Oh, I'm sorry, I completely misread your message. Easiest thing to do would probably be to modify the [storage README](https://github.com/talkiq/gcloud-aio/blob/master/storage/README.rst) since this is a top-level comment, though theoretically any docstrings would show in the [docs](https://talkiq.github.io/gcloud-aio/)!
