### ISSUE TITLE
Include offset and limit in Query repr even if they are 0

### ISSUE THREAD

**Issue by KevinGDialpad** [talkiq/gcloud-aio#162]
These should check for None instead:
https://github.com/talkiq/gcloud-aio/blob/abe2ea915c342df06b69d439b2138b270e574eeb/datastore/gcloud/aio/datastore/query.py#L87-L90

**Comment by TheKevJames** [comment]
Solved in #164 and released as `gcloud-{aio,rest}-datastore==7.0.0`!
