### ISSUE TITLE
get_distribution('gcloud-aio-storage').version call breaks cloud function

### ISSUE THREAD

**Issue by unovongalixor** [talkiq/gcloud-aio#184]
i've been using gcloud-aio-storage in a cloud function to handle parallel uploads with great success, but recently tried deploying and found the cloud function wouldn't deploy with gcloud-aio-storage as a dependency in requirements.txt.

you can verify this by attempting to deploy a hello world example with gcloud-aio-storage in the requirements file.

in my project i've vendorized gcloud-aio-storage and gcloud-aio-auth and hardcoded the versions in both of their __init__.py files

**Comment by eddiedialpad** [comment]
Hello! We had the same problem -- there's a shared dependency between gcloud-aio-storage, and the internal google cloud function worker code -- we both require aiohttp -- who then requires yarl.

The yarl package got an update four days ago that's introduces a change in a function signature -- I'm in the process of making a PR to pin a good version of yarl here -- and also to message aiohttp and yarl about the incompatibility.

For now -- add this to your `requirements.txt` --

`yarl==1.4.2`

**Comment by TheKevJames** [comment]
@unovongalixor the fix @eddiedialpad described should now be released in `gcloud-aio-auth==3.4.1`; updating should do the trick. Let us know if you find any other problems!

**Comment by eddiedialpad** [comment]
@unovongalixor -- I'm planning to undo the yarl version pin in gcloud-aio shortly, since further reading revealed that it's Google Cloud Functions that has a version pin to 1.4.2 -- their doc here lists their version pins: https://cloud.google.com/functions/docs/writing/specifying-dependencies-python
