### ISSUE TITLE
aiohttp version requirement too low

### ISSUE THREAD

**Issue by daniel5gh** [talkiq/gcloud-aio#188]
https://github.com/talkiq/gcloud-aio/commit/d6d3b0f74a428b5083e3b6e9bee32e4d26793c5f introduced using the `ssl` keyword to `aiohttp.TCPConnector`.

The requirements [here](https://github.com/talkiq/gcloud-aio/blob/master/auth/requirements.txt) currently state `aiohttp` must be at least 2.0.0 but this ssl keyword is not available until https://github.com/aio-libs/aiohttp/pull/2628 which is listed under milestone 3.0. I haven't checked but it looks like this `ssl` keyword is added then in version 3 and as such the requirement here should be at least 3.0

**Comment by TheKevJames** [comment]
@daniel5gh great catch, thank you! I will get this updated in #190.
