### ISSUE TITLE
Cannot connect to host metadata.google.internal

### ISSUE THREAD

**Issue by jeremyschiemann** [talkiq/gcloud-aio#192]
Hello,

I'm trying to write to a bucket, I ran `gcloud auth application-default login` and granted access and everything. The default credentials also work because I am able to write to the Bucket with this  https://cloud.google.com/storage/docs/reference/libraries#using_the_client_library

When i'm using the example from gcloud-aio however 

```python
import aiohttp
from gcloud.aio.storage import Storage


    async with aiohttp.ClientSession() as session:
        client = Storage(session=session)

        status = await client.upload(bucket='my-bucket',
                                     object_name='test',
                                     content_type='application/xml',
                                     file_data=body) # body is just some example xml string

        print(status)
```

all im getting is 

``` 
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host metadata.google.internal:80 ssl:default [getaddrinfo failed]
```

Can somebody help/point me into the right direction?

**Comment by Nan2018** [comment]
@jeremyschiemann Did you get this resolved? I got the same error.

**Comment by sorasful** [comment]
@jeremyschiemann  Hello, so what was the problem then ?

**Comment by ivanprado** [comment]
@jeremyschiemann facing the same problem. What was the solution? Thank you.

**Comment by ivanprado** [comment]
Setting manually the env variable 
```
GOOGLE_APPLICATION_CREDENTIALS=/home/your_home/.config/gcloud/application_default_credentials.json
```
worked for me.

**Comment by ivanprado** [comment]
Running `gcloud auth application-default login` worked for me.
