### ISSUE TITLE
How to set content encoding in Storage.upload()?

### ISSUE THREAD

**Issue by 0anton** [talkiq/gcloud-aio#193]
How can I set `content_encoding` with `Storage.upload()`? My use-case: I'm uploading gzipped content. I have to [indicate](https://cloud.google.com/storage/docs/transcoding) that by specifying `Content-Encoding: gzip`. RIght now I use the workaround by using classical sync storage client from google:

    google.cloud.storage.blob.content_encoding = 'gzip'
    google.cloud.storage.blob.patch()

This costs me a second round-trip to GCP and a dependency from the classical library.

I looked the code of Storage.upload() and didn't find anything, which I can use to set required headers.

**Comment by TheKevJames** [comment]
Sorry for missing this issue crop up -- `Storage.upload()` now allows you to do this via [setting the `content_type` parameter](https://github.com/talkiq/gcloud-aio/blob/973fe9785556e0a80007684d284f9091dd0fe89d/storage/gcloud/aio/storage/storage.py#L313).
