### ISSUE TITLE
Cannot set content_encoding metadata using Storage.upload()

### ISSUE THREAD

**Issue by 0anton** [talkiq/gcloud-aio#194]
It seems to me that setting `content_encoding` metadata attribute does not work as expected.

I am using this snippet to set metadata during upload:

            await async_client.upload(BUCKET_NAME, filename,
                                      gzip.compress(payload),
                                      content_type='application/xml; charset=utf-8',
                                      metadata={ 'original-content-length': request.headers['Content-Length'] },
                                      force_resumable_upload=True)

Resulting object does not have metadata:

```
gsutil stat gs://aaa/aaa
    Creation time:          Thu, 20 Aug 2020 08:30:11 GMT
    Update time:            Thu, 20 Aug 2020 08:30:11 GMT
    Storage class:          STANDARD
    Content-Length:         23
    Content-Type:           application/xml; charset=utf-8
    Hash (crc32c):          HsRoNg==
    Hash (md5):             UzQbM5sbGurGKsjtcZ40Rg==
    ETag:                   CKWYie6uqesCEAE=
    Generation:             1597912211672101
    Metageneration:         1
```

Using classical client it works:

        blob = bucket.blob(filename)
        blob.content_encoding = 'gzip'
        blob.metadata = {
            'original-content-length': request.headers['Content-Length']
        }
        blob.patch()

gsutil stat gs://xxx

    Creation time:          Thu, 20 Aug 2020 08:34:56 GMT
    Update time:            Thu, 20 Aug 2020 08:34:56 GMT
    Storage class:          STANDARD
    Content-Encoding:       gzip
    Content-Length:         23
    Content-Type:           application/xml; charset=utf-8
    Metadata:               
        original-content-length:3
    Hash (crc32c):          99cvog==
    Hash (md5):             GjGZ1mlQCU+RRLNiCQTypg==
    ETag:                   CKXD4/WvqesCEAI=
    Generation:             1597912496267685
    Metageneration:         2

**Comment by WoodyFleurant** [comment]
+1 Would be great indeed to be able to send metadata

**Comment by TheKevJames** [comment]
Interesting, this is "supposed to work"! I'll try to find some time to investigate what's going on here -- any more details or thoughts on what we might be doing differently would be appreciated! Just did a quick sanity check and it seems like we're following the isntructions [here](https://cloud.google.com/storage/docs/performing-resumable-uploads)...

**Comment by 0anton** [comment]
Sorry, setting metadata works well. The only thing is missing - it is not possible to set the `content_encoding`, which is a special kind of metadata (not part of the metadata dict, even in the official client).
My question is actually related to #45, which is open and requesting help. So I close this one.
