### ISSUE TITLE
How to authenticate drive api using oauth2.0 client ID ?

### ISSUE THREAD

**Issue by tkda-h3** [talkiq/gcloud-aio#244]
I try to authenticate driva api using oauth2.0 client ID and client secret.
how can I get token by `google-aio-auth` ?

**Comment by TheKevJames** [comment]
The usage patterns should be explained in the auth readme here: https://github.com/talkiq/gcloud-aio/tree/master/auth#usage

tl;dr: 
```python
my_token = await gcloud.aio.auth.Token().get()
```
