### ISSUE TITLE
Storage.copy() doesn't copy Custom Time attribute

### ISSUE THREAD

**Issue by jeremyschiemann** [talkiq/gcloud-aio#316]
Hello,

When I'm copying an object from one bucket to another, the custom time attribute is not set anymore for the new object.
Is this intended and if so what would be the correct way to copy everything? Or is this indeed a bug?

I'm using copy() like this:
```python
await async_client.copy("source_bucket_name", "object_name", "destination_bucket_name", session=SESSION)
```

Thanks for every help!

---
gcloud-aio-storage 5.6.0
python 3.8

**Comment by TheKevJames** [comment]
As of storage v6.2.0, custom metadata should now be correctly copied with that operation. Please let us know if you experience further issues!
