### ISSUE TITLE
ClientResponseError

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#351]
Hi, team!

I start getting this errors once migrated from old datastore library to this one. Code logic was not changed.

Error:
```
409, message='Conflict: {\n  "error": {\n    "code": 409,\n    "message": "too much contention on these datastore entities. please try again. entity groups: [(app=test-project1, Restaurant, 5880086327459840)]",\n    "status": "ABORTED"\n  }\n}\n', url=URL('https://datastore.googleapis.com/v1/projects/test-project1:commit')
```

Pseudo Code:
```python
entity = await get_entity()
entity = await update_entity()
return response
```

Any ideas?
What is the correct way to use this library for microservice? Instantiate client once on service startup and close connection on service shutdown or open/close client for each datastore request?

**Comment by KevinGDialpad** [comment]
Hi Max,

This error is returned by the API (the library only forwards it). It is complaining about contention (too many updates to the same entity - see [limits](https://cloud.google.com/datastore/docs/concepts/limits)), but in my experience you get the same error in case of a transaction collision (two transactions trying to update the same entity). My guess is that your code does one of these two things.

> What is the correct way to use this library for microservice? Instantiate client once on service startup and close connection on service shutdown or open/close client for each datastore request?

I don't think there is a correct way. The library is merely a Python client for some Google APIs and it's not opinionated. That said, your first solution makes more sense to me.

**Comment by umax** [comment]
Thank you @KevinGDialpad for explanations. Let's close this issue.
