### ISSUE TITLE
Entity not found without query ordering

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#353]
Hi, team!

I found some strange behaviour, I don't know exactly is it expected behaviour or bug. Please clarify.
There are 2 functions. One of them order results, another one - not. The first one match value, another one - no.
In other words: when I use ordering for query - query result contains expected value. When I don't use ordering for query - query result does not contain expected value.

### Code example
```python
import asyncio

from gcloud.aio.datastore import Datastore, Direction, PropertyOrder, Query


async def without_ordering(client, name):
    query = Query(kind='Restaurant')
    result = await client.runQuery(query)
    for er in result.entity_results:
        if er.entity.properties['restaurant_name'] == name:
            return er.entity

    return None


async def with_ordering(client, name):
    query = Query(
        kind='Restaurant',
        order=[PropertyOrder(
            prop='restaurant_name',
            direction=Direction.ASCENDING,
        )],
    )
    result = await client.runQuery(query)
    for er in result.entity_results:
        if er.entity.properties['restaurant_name'] == name:
            return er.entity

    return None


async def main():
    _client = Datastore('kitchenhub-app-prod', 'credentials-prod.json')

    print(await without_ordering(_client, 'Moo Burger') is None)
    print(await with_ordering(_client, 'Moo Burger') is None)
    await _client.close()


if __name__ == '__main__':
    asyncio.run(main())
```

## Run results
```shell
$ python main.py
True
False
```

**Comment by KevinGDialpad** [comment]
Weird.

To find out whether the discrepancy comes from the library or the datastore, look at the HTTP request that's sent by the library and compare the JSON body to [what the API expects](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/runQuery).

If it's the datastore, there may be more clues in the full response that it returns.

**Comment by TheKevJames** [comment]
@umax this looks like it may be a pagination issue -- note that `runQuery()` returns a `QueryResultBatch` instance ([see code](https://github.com/talkiq/gcloud-aio/blob/5335b42f7025882c2304c8d5285e4e14ddcf493c/datastore/gcloud/aio/datastore/query.py#L151)). Most relevantly, it has a `more_results` field which can be used to check for subsequent pages. (note as well that you can adjust the arguments to the `Query` constructor to change how you paginate or to fetch further pages)

I suspect `Moo Burger` is being returned in a page other than the first when you apply ordering.

**Comment by TheKevJames** [comment]
Closing as not an issue.
