### ISSUE TITLE
[Feature Request - Storage] Changing the metadata while copying the object

### ISSUE THREAD

**Issue by langered** [talkiq/gcloud-aio#362]
When I copy a gcs object from one to another location, the new object should get other metadata.
In the official documentation of GCP, a data body can be send with the request:
https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite#request-body

Sadly, the current version does not support sending a data body with the public function `copy`: https://github.com/talkiq/gcloud-aio/blob/47b7d8f86ace49c74dbefbfb3b26ad2a08ef7aa5/storage/gcloud/aio/storage/storage.py#L149-L153

I opened a PR with my proposal for extending the copy function with a data body:
https://github.com/talkiq/gcloud-aio/pull/361

I am open to any feedback and discussion! I am aware that I "expose" the whole data body in the endpoint and I am open to reduce this to only metadata if required.

**Comment by TheKevJames** [comment]
Hi @langered! I've merged your PR and released it as `v6.2.0`. Heads up I had to change the signature of the `copy` method to a dictionary rather than a string in order to supported nested metadata -- see abd56ce7709f1637bba4a3e2d401a3261e43e0dc for more info.
