### ISSUE TITLE
is:issue is:open Can we use this library to directly upload bytes data from aiohttp ? Official api has something called upload_from_string

### ISSUE THREAD

**Issue by janaki-sasidhar** [talkiq/gcloud-aio#364]
is:issue is:open Can we use this library to directly upload bytes data from aiohttp ? Official api has something called upload_from_string

**Comment by TheKevJames** [comment]
You absolutely can: this library offers both a `storage.upload_from_filename()` and a `storage.upload()` command, the latter of which accepts any `bytes`, `str`, or `IO` type for the `file_data` argument.

(I assumed this was a question about `gcloud-aio-storage`, please feel free to let me know if I was wrong!)
