### ISSUE TITLE
gcloud-aio-storage supports downloading data from gcs?

### ISSUE THREAD

**Issue by ryo-matsuzaka** [talkiq/gcloud-aio#378]
Hi. I have a question about this project.

In [this page](https://pypi.org/project/gcloud-aio-storage/), there is a usage description like

> Usage
> To upload a file, you might do something like the following:

I am searching async tools for downloading from GCS.
Does this tool support the task?

**Comment by TheKevJames** [comment]
Yes indeed -- see the [various download methods](https://github.com/talkiq/gcloud-aio/blob/9d0e4ac9665e7e6c07ce206cfbd7dc071659812e/storage/gcloud/aio/storage/storage.py#L227-L279) for varying usecases, eg. in case you are looking to download to a file, or a stream, or an object in memory.

**Comment by ryo-matsuzaka** [comment]
I am very happy to hear that.
Thank you very much!
