### ISSUE TITLE
Pub/Sub publisher

### ISSUE THREAD

**Issue by mackeyja92** [talkiq/gcloud-aio#38]
Looks like the publisher side of pub sub is not implemented, is there plans for this?

**Comment by TheKevJames** [comment]
v1.2.0 of ``gcloud-aio-pubsub`` now has a (fairly barebones for now) Publisher: https://github.com/talkiq/gcloud-aio/tree/master/pubsub#publisher

Closing out this ticket, but happy to accept any contributions to help add more functionality!
