### ISSUE TITLE
Exclude value from indexes

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#384]
Hi, team!

I want to create an entity with some fields excluded from indexes:

```
properties = {
    'a': 111,
    'b': Value(value='bbb', exclude_from_indexes=True)
}
key = Key(PROJECT_ID, [PathElement('TestEntity')])
await client.insert(key, properties)

entity = await client.runQuery(....)
print(entity.to_repr())
```
->
```
{'key': {'partitionId': {'projectId': 'dev', 'namespaceId': ''}, 'path': [{'kind': 'TestEntity', 'id': '7955'}]}, 'properties': {'a': {'excludeFromIndexes': False, 'integerValue': 111}, 'b': {'excludeFromIndexes': False, 'stringValue': 'bbb'}}}
```

How to exclude property from indexes on entity creation?

**Comment by TheKevJames** [comment]
Hi @umax! 

I've been unable to reproduce this one -- as far as I can tell, you're doing everything exactly correct there. I've run the same sample code against my own GCP projects and `b` seems to be properly excluded from the indexes. Is there any more info you might be able to provide to help debug?

**Comment by TheKevJames** [comment]
Closed as stale.
