### ISSUE TITLE
How to test Storage against the emulator fsouza/fake-gcs-server

### ISSUE THREAD

**Issue by sorasful** [talkiq/gcloud-aio#396]
Hello ! 

I'm currently using `gcloud-aio-storage` and I need to add some tests in my code. I read that we can use an emulator and the documentation gives the commands : 

Documentation link : https://github.com/talkiq/gcloud-aio/blob/master/storage/README.rst 

```bash
docker run -d -p 4443:4443 -v $PWD/my-sample-data:/data fsouza/fake-gcs-server
export STORAGE_EMULATOR_HOST='0.0.0.0:4443'
```

And when I run the code in the example I get : 

```python
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4443 ssl:default [Connect call failed ('0.0.0.0', 4443)]
```

And it's said is the documentation : "Note that some emulation systems require disabling SSL -- if you're using a custom http session, you may need to disable SSL verification." 

But how can we do this if we use the given code in the example ? 

Thanks !

**Comment by TheKevJames** [comment]
Ah, I see a bit of competing info in our docs. I think I know what the issue is, but could you please confirm everything works _if you **let gcloud-aio handle the session management**?

Example:

Instead of
```
async with aiohttp.ClientSession() as session:
    client = Storage(session=session)
```
please do:
```
async with Storage() as client:
```

**Comment by TheKevJames** [comment]
Ah, interesting. If you happen to discover what the behaviour difference is on Windows, please let us know -- I'd love to add any workaround etc to our documentation!
