### ISSUE TITLE
Warning when uploading large data using multipart

### ISSUE THREAD

**Issue by bruchar1** [talkiq/gcloud-aio#404]
In aio.storage, in the `_upload_multipart()` function, the stream is converted to `bytes`. It cause aiohttp to use BytesPayload, which raises a warning if the data size is greater than 1MB. 

I think the `post` in `_upload_multipart()` should wrap body data into a `io.BytesIO` instead, to prevent that warning.

**Comment by TheKevJames** [comment]
That makes sense to me! The only potential issue I see here is that we need to be able to support both Py2 and Py3 -- I have the vague recollection that `BytesIO` used to work a bit differently, so we'll need to be careful to test both cases.

**Comment by bruchar1** [comment]
Isn't aio driver only working on python 3?

**Comment by TheKevJames** [comment]
@bruchar1 that is correct, but the `gcloud-rest-storage` library is generated from the same codebase and so types need to work in that case as well. It is possible to have behaviour vary based on the `BUILD_GCLOUD_REST` compilation flag, but as much as possible keeping the two codebases in sync helps significantly with maintenance efforts.
