### ISSUE TITLE
Support for upload of files larger than 5 mb

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#41]
According to google documentation the "resumable upload" must be used for files larger than 5 mb. Suggest to ether:
- add an `upload_resumable` method to storage.py
- add a switch to `upload` which determines which upload type to use. In case the file size is larger than 5mb automatically use upload_resumable

**Comment by JensMadsen** [comment]
Question: why is input data converted to string? https://github.com/talkiq/gcloud-aio/blob/a46221f4d8e90a9ac9dcf1a98dfe87e2e7821708/storage/gcloud/aio/storage/storage.py#L94

would it be an idea to force the user to provide MIME type or perhaps autodetect the type?

**Comment by JensMadsen** [comment]
.... or actually it works if the content-type is set n the header but I would suggest to rename the following methods: storage.download  -> storage.download_metadata and storage.download_ad_string -> storage.download :-)

**Comment by TheKevJames** [comment]
> why is input data converted to string? 

This library started as an internal utility and there's still a few of these specific-to-our-use-case chunks left around. We'd absolutely love to allow uploads of any type! This method currently assumes the file to-be-uploaded is a JSON object, but that of course is far too specific. Happy to accept any PRs for generalizing this!

I agree re: renaming `storage.download -> storage.download_metadata`, but I think `storage.download_as_string` is good as is, since it returns `response.text()`. We should either have all of `download_as_string`, `download_as_bytes`, `download_as_json` which calls the correct `response` methods, or we should do do the rename and add a parameter for allowing the user to determine the format (ie. `def download(..., kind='string') # kind in {'string', 'json', ...}` or something like that).

**Comment by JensMadsen** [comment]
What about testing? I have written small integration tests which tests against my own bucket, but how do you prefer that I do that when I am an "outside" collaborator? At the moment I inject the bucket name together with the CRED and PROJECT as an env var. Is that a good idea? I push my current code to the fork in a moment then you guys can take a look and see if you want  to merge it in :-)

**Comment by JensMadsen** [comment]
I am so stupid. I wanted to do it the test-driven way but failed to write this kind of test
```# exceed googles 5 MB upper limit for simple upload interface
file_size = 10 * 1024 * 1024
data_to_upload = os.urandom(file_size)


@pytest.mark.asyncio
@pytest.mark.parametrize('force_resumable_upload', [True, False, None])
async def test_upload_big_file(force_resumable_upload):
    object_name = f'big_file.bin'

    async with aiohttp.ClientSession() as session:
        storage = Storage(PROJECT, CREDS, session=session)
        res = await storage.upload(BUCKET_NAME, object_name, data_to_upload,
                                   force_resumable_upload=force_resumable_upload)

        # TODO test choice of upload method
        # assert failed simple upload method -> file is too large
        await storage.delete(BUCKET_NAME, res['name'])
```
It turns out that the European endpoint repeatedly accepts 10 mb files using the simple upload method. So to some extend waste of time... :-(

**Comment by TheKevJames** [comment]
Ouch! A quick glance through the Google docs couldn't find anything about the 10MB thing, but I wonder if there's some sort of endpoint we should be querying to set that 5MB value then (eg. `MAX_UPLOAD_SIZE = bucket.query_google_for_max_size()`)? Or even something we could do to hardcode it based on region (eg. `MAX_UPLOAD_SIZE = {'eu': 10}.get(REGION) or 5`)?

**Comment by JensMadsen** [comment]
I can upload files bigger than 10 mb as well without getting an error. quote google docs: `If you need to provide metadata for the file, you can use multipart upload or resumable upload instead. For larger files (more than 5 MB) or less reliable network connections, use resumable upload.` I have been looking through some stackoverflow answers apparently people have experienced 413 error when trying to upload large files. I dont. I any case it makes sense to have a resumable upload when dealing with large files in case the network connection is not perfect.

**Comment by TheKevJames** [comment]
Got it. Ok, then let's keep the 5 MB default specified in your PR, that seems like a very reasonable value anyway.

With regards to your test, I suppose this is more cases where _actually hitting GCP_ in our tests is hurting us. We really need to start mocking these things, eg. mocking `requests` to return a 413 then test accordingly.

**Comment by TheKevJames** [comment]
Fixed, will be released in the next version, after your other PR goes in. Thanks again! :)
