### ISSUE TITLE
How to rename file? 

### ISSUE THREAD

**Issue by maitham** [talkiq/gcloud-aio#410]
Hey, 

Great library, whats the best way to rename_blob using this library?

**Comment by TheKevJames** [comment]
Hi @maitham -- using a `copy()` (https://github.com/talkiq/gcloud-aio/blob/26a34a3a2ed1e22622235e16ee5c9c35a3e745c3/storage/gcloud/aio/storage/storage.py#L151) and a `delete()` (*https://github.com/talkiq/gcloud-aio/blob/26a34a3a2ed1e22622235e16ee5c9c35a3e745c3/storage/gcloud/aio/storage/storage.py#L218) would probably be the most straightforward. Alternatively, you could use `patch_metadata()` to change the name directly (https://github.com/talkiq/gcloud-aio/blob/26a34a3a2ed1e22622235e16ee5c9c35a3e745c3/storage/gcloud/aio/storage/storage.py#L608).
