### ISSUE TITLE
Support for Impersonated Credentials

### ISSUE THREAD

**Issue by bcwaldon** [talkiq/gcloud-aio#421]
I am interested in using gcloud-aio-storage, but I also need to use impersonated service account credentials. My current code works with the non-asyncio google-cloud-storage package, which in turn utilizes the google-auth package. Here is a direct reference to the bit of that auth lib I am currently using: https://google-auth.readthedocs.io/en/master/reference/google.auth.impersonated_credentials.html

My question here is 1) is there a way to utilize SA impersonation today with gcloud-aio-storage? and 2) if not, would it be possible to add support for this given the current gcloud-aio library architecture?

**Comment by TheKevJames** [comment]
Hi @bcwaldon! As far as I understand from those docs: no, `gcloud-aio-*` does not currently support impersonated credentials. That said, we would be more than happy to accept a PR implementing them; I believe that would mostly come down to modifying how a `Token` is [constructed](https://github.com/talkiq/gcloud-aio/blob/8cd31c6a0157c8e4272b2248ccb639abf8238b7e/auth/gcloud/aio/auth/token.py#L96), perhaps by adding in a `target_principal` optional parameter or such.

**Comment by kevinaud** [comment]
Perhaps it would make sense to interface more directly with the google-auth package? i.e. maybe we could just let you pass a google.auth.credentials.Credentials into the Token constructor.

then gcloud-aio doesn't need to know/care where the instance came from (default creds, service account file, impersonation, etc)

**Comment by m1racoli** [comment]
> Perhaps it would make sense to interface more directly with the google-auth package? i.e. maybe we could just let you pass a google.auth.credentials.Credentials into the Token constructor.
> 
> then gcloud-aio doesn't need to know/care where the instance came from (default creds, service account file, impersonation, etc)

In general I agree with the sentiment, but I believe one issue is that the methods of Google's Credentials classes are blocking and cannot used in async environments like that.

**Comment by TheKevJames** [comment]
Solved and released in v5.2.0. Thanks all!

With respect to tracking upstream, I agree with the goal but we do need to maintain implementation separation for the reason @m1racoli provided. If folks have suggestions / want to submit PRs for ways we can keep better in sync while still being able to stick with the alternative transport backends, those would be highly appreciated!
