### ISSUE TITLE
Storage upload takes stream as input

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#44]
Memory efficient approach. Should not need to load large files into memory. Inspiration here: https://github.com/GoogleCloudPlatform/google-resumable-media-python/blob/master/google/resumable_media/_upload.py

Also, consider to support uploading in chunks for very large files (> 100 mb?)

**Comment by TheKevJames** [comment]
Fixed in 137ea7afd7052cd63dc5409a03970dc5dcec5ac6. Thanks again!
