### ISSUE TITLE
gcloud-aio-storage pypi pipeline failed

### ISSUE THREAD

**Issue by vector-ml** [talkiq/gcloud-aio#447]
Just wanted to mention that the pypi upload of `gcloud-aio-storage` version `6.4.0` failed https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/1732/workflows/2dd0e6f1-bb86-411f-8f55-237405c121a9/jobs/35715 . can someone retry or resolve the issue?

**Comment by TheKevJames** [comment]
@vector-ml thanks for calling this out! I finally managed to track down the issue, and `gcloud-aio-storage` should be [correctly building again](https://app.circleci.com/pipelines/github/talkiq/gcloud-aio/1848/workflows/b06a26d3-d7e8-41a8-8228-2a2cc2f28251)!
