### ISSUE TITLE
Upload as gzip

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#45]
gzipping files before upload could lead to a significant performance boost. see: 
- https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance
- https://cloud.google.com/storage/docs/transcoding

- [ ] `Content-Encoding: gzip` must set  in headers
- [ ] when use `gzip = True` -> zip data before upload (https://docs.python.org/3/library/gzip.html or use built-in gzip of aiohttp?)
- Not sure how this would work with streams?

**Comment by TheKevJames** [comment]
Good idea! Just like in [this comment](https://github.com/talkiq/gcloud-aio/issues/41#issuecomment-440078798) I think we'd want to provide a:
```
Storage.upload(..., zipped: Optional[bool] = None)
```
where:
- `zipped = False` - current behaviour
- `zipped = True` - run gzip, set `content-encoding`, etc
- `zipped = None` (default) - allow us to chose, which we might do based on file size etc.

**Comment by TheKevJames** [comment]
Support has been added in `gcloud-*-storage` v9.3.0!
