### ISSUE TITLE
How to gracefully close Pub/Sub subscriber

### ISSUE THREAD

**Issue by HJulio** [talkiq/gcloud-aio#473]
Hi!

I reviewed the code and there is an exception that triggers a graceful shutdown. 

https://github.com/talkiq/gcloud-aio/blob/57c6a922d85bb375cdfcb247fbc5751308c49185/pubsub/gcloud/aio/pubsub/subscriber.py#L276

How can I call this outside the "subscribe" function or in the handler?  

Example: I want to close the subscriber after a specific signal or a specific exception.

I tried to raise the exceptions in the handler, close the subscriber session, etc but the subscribe continued pulling messages. 

Thank you!

**Comment by janczarek99** [comment]
Hello,

If you want to call it outside the loop you can do it f.e. like that - run subscribe as task and then cancel it on some case.
Little code snippet

```Python
import asyncio
from gcloud.aio.pubsub import subscribe

async def main():
  subscribe_task = asyncio.ensure_future(
    subscribe(subscription="...", handler=some_callback, subscriber_client=some_subscriber_client)
  )

  # Here goes your normal code, some processing or other tasks etc.
  # Let's say we want to stop our subscriber after some time (5s)
  for _ in range(10):
    await asyncio.sleep(0.5)

  subscribe_task.cancel()  # This is how you can cancel your task which will cause `asyncio.CancelledError`.
```

**Comment by TheKevJames** [comment]
Thanks for answering this one @janczarek99, I've just included your answer in our official docs.
