### ISSUE TITLE
storage doesn't support download of binary files

### ISSUE THREAD

**Issue by msalib** [talkiq/gcloud-aio#51]
If you try to use .download or .download_as_string with binary file, the request will fail because the download method calls resp.text() which tries to decode the raw data.

**Comment by TheKevJames** [comment]
This is already being worked on as a piece of #46. Expect this for the next `gcloud-aio-storage` release!

**Comment by TheKevJames** [comment]
This is now resolved with the new `Storage.download()` method (rather than `download_as_string()`. Expect it in the next `gcloud-aio-storage` release!
