### ISSUE TITLE
License files were deleted as part of migration to poetry

### ISSUE THREAD

**Issue by xylar** [talkiq/gcloud-aio#517]
It appears that license files were removed in https://github.com/talkiq/gcloud-aio/commit/bee30d049e7d52c7d859184987e0ebe9f425104a.  I presume that wasn't intentional.  They should be getting included in PyPI packages.

**Comment by TheKevJames** [comment]
Thanks for the report, but my understanding is that this is no longer necessary as the licenses are specified via the pyproject.toml files, eg. [here](https://github.com/talkiq/gcloud-aio/blob/9f61001ce650e263220ca0e2c1ba480242571cdb/auth/pyproject.toml#L9). If I'm reading [PEP-621](https://peps.python.org/pep-0621/#license) correctly, this value can either be a file path (as we used to have) or the name of a well-known license (see, for example, [this list](https://python-poetry.org/docs/pyproject/#license) from poetry).

Have I made a mistake somewhere here?

**Comment by TheKevJames** [comment]
Oh, and as an aside -- thanks for setting up conda feedstocks for this project! We appreciate it :)

**Comment by xylar** [comment]
@TheKevJames, thanks.  I haven't come across this before.  Every repo I can find that uses a `pyproject.yaml` still includes a LICENSE file.  I have asked for some feedback on conda-forge's gitter channel: https://gitter.im/conda-forge/conda-forge.github.io.  Let's see what they suggest.

**Comment by xylar** [comment]
@TheKevJames, the response I got on Gitter was:
> [Jaime Rodríguez-Guerra](https://matrix.to/#/@jaimergp:matrix.org?utm_source=gitter)
> I've never seen this argued, so I'd still distribute the old license file. It's ultimately up to the license itself whether it's required or not, but I'd even distribute the license file for clarity even when it's not required.
> 
> That said, MIT license states:
>
>> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
>
> So it's not like it's an option :D
> 
> Whether you include the file or not it's not up to the pyproject metadata either, I'd say.

It seems like you probably do need to include the license file because that is a requirement of the MIT license.  Other licenses might or might not require that but I think most do.

**Comment by TheKevJames** [comment]
Ah, awesome, TIL. Thanks for checking on this and I appreciate the flag. I've reintroduced them in c591d282.

**Comment by xylar** [comment]
Great, thanks! As I said, this was new to me as well.
