### ISSUE TITLE
ensure outside contributors can run integration tests

### ISSUE THREAD

**Issue by TheKevJames** [talkiq/gcloud-aio#53]

**Comment by JensMadsen** [comment]
Any progess here :-) Now unless you hack the tests a bucket to which I have no credentials file is used.

**Comment by TheKevJames** [comment]
Sorry @JensMadsen, haven't had a chance to get to this yet. Hopefully soon, but we've had a busy quarter here so far, so not as much time for OSS contributions as I'd like :)
