### ISSUE TITLE
Security vulnerability in future package. Should it be removed

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#563]
Vulnerability see: https://github.com/PythonCharmers/python-future/issues/612

The package will most likely not be patched and was meant to ease the transition from Python 2 to Python 3, so perhaps just remove the dependency all together?

**Comment by TheKevJames** [comment]
I've updated to future v0.18.3 which addresses this CVE: #573. Note though that python-future is used only as a build tool and as such we were not affected by this issue.

For now, we still need this package as we build Python 2 compatible bindings (`gcloud-rest-*`) of this package. We will definitely drop `future` once we decide to drop py2 support!

Thanks for the report :)
