### ISSUE TITLE
raise exception when provided credentials file is not found

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#61]
When a wrong path to a credentials file is given no error is thrown in auth.py:45-51. I argue that in the case where the user has provided a specific path to the credentials file and the path is not correct we shoudl throw an error instead of silently "hope" that teh right credentials are stored in an env var :-) I can do the fix If you like i.e. catch and raise a `FileNotFoundError?

**Comment by JensMadsen** [comment]
PR #62

**Comment by TheKevJames** [comment]
Ah -- in this case, we're following the same flow that the standard Google libraries do: see [the release notes for auth v2.0.0](https://github.com/talkiq/gcloud-aio/releases/tag/auth-2.0.0).

Most relevantly here, the empty response from that method is used to check whether we should use the GCE metadata service for authentication.

We might want to raise the `FileNotFoundError` _only_ in the case where the user has explicitly passed a file which does not exist, but we definitely do not want that error to be the standard case (nor would we want that error raised when we've fallen back to constructing the `~/.config/gcloud` path!)

**Comment by JensMadsen** [comment]
ok . in that case we should check in the beginning of the method then ? I try to adpat PR
