### ISSUE TITLE
Vulnerable OpenSSL included in cryptography wheels

### ISSUE THREAD

**Issue by Arthur264** [talkiq/gcloud-aio#625]
gcloud-aio uses cryptography==40.0.2 which has vulnerability. 

pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.

If you are building cryptography source ("sdist") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.

The earliest fixed version is cryptography==41.0.0.

**Comment by TheKevJames** [comment]
Updated to support `cryptography v41` as of `auth` v`4.2.2`. Thanks for the report!
