### ISSUE TITLE
Authentication without service json

### ISSUE THREAD

**Issue by vijayendra** [talkiq/gcloud-aio#64]
I was trying to run asyncio storage client in google cloud kubernetes cluster with default auth without service file. Is there any way to authenticate storage client without service file?

**Comment by TheKevJames** [comment]
Hi @vijayendra! As of [gcloud-aio-auth version 2.0.0](https://github.com/talkiq/gcloud-aio/releases/tag/auth-2.0.0), this library should support authentication via the Google Compute Engine metadata service, eg. without a service file. Using the library without passing in a service account should fall back to this method, which should work on a GKE cluster. Please update to version 2.0.0 and feel free to re-open this ticket if you run into any issues there!
