### ISSUE TITLE
typing information not found by mypy due to missing __init__.py

### ISSUE THREAD

**Issue by jstriebel** [talkiq/gcloud-aio#67]
Having installed `gcloud-aio-auth` (version `2.0.1`) and using it, mypy does not find the module, logging `Cannot find module named 'gcloud.aio.auth'`.
This is due to the missing `__init__.py` in `gcloud` and `gcloud/aio` (`gcloud/aio/auth/__init__.py` exists). Adding them to the package fixes this. Probably the files are lost in the `setup.py`/`twine` process.

**Comment by TheKevJames** [comment]
Thanks for the bug report! Looks like we had a typo in our MANIFEST.in files which was causing the `__init__.py` files to get skipped. Going forwards, they should be included in all future `gcloud-aio-*` releases.
