### ISSUE TITLE
Package not update on pypi? why

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#68]
the code on giithub and on pypi is out of sync (e.g. storage.py _preprocess_data). Is that on purpose?

**Comment by TheKevJames** [comment]
Hey @JensMadsen -- I've just triggered an update to all the `gcloud-aio-*` libraries; you should see them on PyPI shortly!

**Comment by JensMadsen** [comment]
great. Is it worth automating?

**Comment by TheKevJames** [comment]
The process is indeed 99% automated -- the only part of the release test which is not be automated is having a human do a double-check of all changes and make sure the regression test suite gets run. We'd always love to get more of these tests automated -- and contributions are welcome there! -- but haven't had the manpower to dedicate to this task.
