### ISSUE TITLE
Working example for cloud storage

### ISSUE THREAD

**Issue by adamshamsudeen** [talkiq/gcloud-aio#84]
Can you please share a working example for cloud storage? 
I'm got an error when I ran the smoke test code.
`aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'`

**Comment by TheKevJames** [comment]
Writing up some more complete docs is definitely on our TODO list -- marking this one as "help wanted" to hopefully get some community help :)

In the meantime, just a sanity check: the exact bucket names etc in the smoke test would be referencing our internal test buckets which you would likely not have access to; make sure that, and the object name, and the project name, etc, is all configured for your use-case.

If you have a code snippet for the 404 you're experiencing, I'd be happy to help debug!

**Comment by adamshamsudeen** [comment]
I got it working. How can I start contributing to the Docs?

**Comment by TheKevJames** [comment]
For now, a PR modifying the "Usage" section of the relevant README would be awesome. I'd be happy to review any docs improvements like that!

**Comment by adamshamsudeen** [comment]
I have submitted a PR #111 , please let me know id I should make any changes.

**Comment by TheKevJames** [comment]
#111 has (long since) been merged, closing the ticket!
