### ISSUE TITLE
Token should accept the service data directly

### ISSUE THREAD

**Issue by rubik** [talkiq/gcloud-aio#92]
In my case the JSON credentials are not in a file, they are in memory. It would be ideal if the token object also accepted credentials directly. Right now I have to write them to a temporary file.

**Comment by TheKevJames** [comment]
Would something like
```
service_file = io.StringIO(json.dumps(service_data))
token = Token(service_file)
```
do the trick for you?

I've seen your linked PR and am just a bit leery of adding more code to maintain if the above could solve the problem -- let me know if there's a limitation to that approach, and I'd be happy to review your PR!

**Comment by rubik** [comment]
Unfortunately that does not work, because `get_service_data` always calls `open()` on its argument:
https://github.com/talkiq/gcloud-aio/blob/3ebccc75022ab527bb7ed2a82cceb8b64437e02c/auth/gcloud/aio/auth/token.py#L50-L52

Maybe another solution is to check whether `service` is an instance of `io.IOBase` and call `.read()` directly on that.

**Comment by TheKevJames** [comment]
Ah, good call, I'd completely forgotten the `open` call in my check (I was reading that block as simply `json.loads(service_file.read())`). Makes sense -- either doing the type check or catching the `TypeError` on `open(io.IOBase, ...)` would be fantastic.

**Comment by rubik** [comment]
@TheKevJames That is reasonable, I'll do that.
